/// Flutter icons HeroIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HeroIcons
///      fonts:
///       - asset: fonts/HeroIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HeroIcons {
  HeroIcons._();

  static const _kFontFam = 'HeroIcons';
  static const String? _kFontPkg = null;

  static const IconData alice_on =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alice_off =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sinbad_on =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arthur_on =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medusa_off =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sinbad_off =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medusa_on =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arthur_off =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
